/* Discover DFW — shared geography + city data.
   ALL market figures (prices, $/sqft, DOM, YoY, populations, ratings, commute minutes)
   are PLACEHOLDERS to be replaced with live data. */
window.DFW = (function () {
  // County polygons as [lon, lat] rings (simplified — North Texas counties are near-rectangular)
  var counties = [
    { id: 'denton', name: 'Denton', labelText: 'DENTON COUNTY', label: [-97.28, 33.375], core: 1, tone: 0,
      blurb: 'Lake towns, horse ranches, and the fast-growing 35W corridor.',
      poly: [[-97.40, 33.43], [-96.84, 33.43], [-96.84, 33.00], [-97.40, 33.00]] },
    { id: 'tarrant', name: 'Tarrant', labelText: 'TARRANT COUNTY', label: [-97.435, 32.635], core: 1, tone: 1,
      blurb: 'Cowtown grit, walkable mid-cities, and big-value neighborhoods.',
      poly: [[-97.55, 33.00], [-97.035, 33.00], [-97.035, 32.555], [-97.55, 32.555]] },
    { id: 'wise', name: 'Wise', labelText: 'WISE COUNTY', label: [-97.66, 33.375], core: 1, tone: 2,
      blurb: 'Lakes, ranchland, and the pink courthouse — the metroplex’s western frontier.',
      poly: [[-97.92, 33.43], [-97.40, 33.43], [-97.40, 33.00], [-97.92, 33.00]] },
    { id: 'collin', name: 'Collin', labelText: 'COLLIN COUNTY', label: [-96.42, 33.375], core: 1, tone: 1,
      blurb: 'Boomtown corridor — corporate HQs, top-rated schools, master plans.',
      poly: [[-96.84, 33.43], [-96.295, 33.43], [-96.295, 33.00], [-96.84, 33.00]] },
    { id: 'dallas', name: 'Dallas', labelText: 'DALLAS COUNTY', label: [-96.66, 32.615], core: 1, tone: 2,
      blurb: 'The urban core — skyline high-rises to first-ring family streets.',
      poly: [[-97.035, 33.00], [-96.52, 33.00], [-96.52, 32.555], [-97.035, 32.555]] },
    { id: 'rockwall', name: 'Rockwall', labelText: 'ROCKWALL CO.', label: [-96.345, 32.885], tone: 0,
      blurb: 'Lakeside living on Ray Hubbard\u2019s east shore.',
      poly: [[-96.52, 33.00], [-96.295, 33.00], [-96.295, 32.82], [-96.52, 32.82]] },
    { id: 'kaufman', name: 'Kaufman', labelText: 'KAUFMAN COUNTY', label: [-96.20, 32.60], tone: 1,
      blurb: 'Room to grow east of the loop — new roofs, small-town squares.',
      poly: [[-96.52, 32.82], [-96.295, 32.82], [-96.295, 32.90], [-96.06, 32.90], [-96.06, 32.52], [-96.16, 32.52], [-96.16, 32.38], [-96.52, 32.38]] },
    { id: 'ellis', name: 'Ellis', labelText: 'ELLIS COUNTY', label: [-96.85, 32.295], tone: 0,
      blurb: 'Rolling blackland prairie and courthouse-square towns.',
      poly: [[-97.09, 32.555], [-96.52, 32.555], [-96.52, 32.38], [-96.60, 32.33], [-96.73, 32.17], [-96.88, 32.24], [-97.09, 32.36]] }
  ];

  // Lakes — loose blobs, drawn puffy with round joins
  var lakes = [
    { name: 'Lewisville Lake', label: [-97.005, 33.135],
      pts: [[-97.02, 33.09], [-97.045, 33.13], [-97.02, 33.185], [-96.975, 33.215], [-96.94, 33.17], [-96.955, 33.115], [-96.985, 33.085]] },
    { name: 'Grapevine Lake', pts: [[-97.09, 32.958], [-97.055, 32.985], [-97.02, 32.975], [-97.03, 32.952]] },
    { name: 'Eagle Mountain Lake', pts: [[-97.475, 32.86], [-97.49, 32.90], [-97.47, 32.945], [-97.445, 32.91], [-97.455, 32.87]] },
    { name: 'Lake Bridgeport', pts: [[-97.845, 33.05], [-97.86, 33.10], [-97.835, 33.15], [-97.805, 33.11], [-97.82, 33.06]] },
    { name: 'Benbrook Lake', pts: [[-97.47, 32.60], [-97.45, 32.635], [-97.43, 32.61], [-97.45, 32.585]] },
    { name: 'Joe Pool Lake', pts: [[-97.03, 32.60], [-97.01, 32.645], [-96.98, 32.62], [-97.00, 32.585]] },
    { name: 'Lake Ray Hubbard', label: [-96.515, 32.875],
      pts: [[-96.545, 32.82], [-96.52, 32.86], [-96.50, 32.905], [-96.475, 32.935], [-96.51, 32.945], [-96.535, 32.90], [-96.555, 32.855]] },
    { name: 'Lavon Lake', label: [-96.45, 33.115],
      pts: [[-96.475, 33.035], [-96.49, 33.09], [-96.465, 33.15], [-96.43, 33.185], [-96.415, 33.12], [-96.445, 33.06]] },
    { name: 'Lake Waxahachie', pts: [[-96.80, 32.355], [-96.775, 32.375], [-96.755, 32.355], [-96.775, 32.335]] }
  ];

  // Major corridors — simplified from real DFW alignments (tollways dashed)
  var roads = [
    { n: 'I-35', w: 2.1, pts: [[-97.175, 33.43], [-97.174, 33.363], [-97.15, 33.28], [-97.128, 33.23], [-97.115, 33.205]] },
    { n: 'I-35E', w: 2.1, pts: [[-97.115, 33.205], [-97.085, 33.15], [-97.03, 33.09], [-97.006, 33.046], [-96.99, 33.00], [-96.945, 32.955], [-96.90, 32.925], [-96.865, 32.88], [-96.83, 32.83], [-96.81, 32.79], [-96.815, 32.73], [-96.835, 32.65], [-96.85, 32.55], [-96.86, 32.46], [-96.87, 32.40], [-96.90, 32.30], [-96.93, 32.17]] },
    { n: 'I-35W', w: 2.1, pts: [[-97.115, 33.205], [-97.155, 33.155], [-97.19, 33.10], [-97.23, 33.06], [-97.27, 33.02], [-97.29, 32.96], [-97.31, 32.90], [-97.32, 32.84], [-97.325, 32.78], [-97.32, 32.72], [-97.33, 32.66], [-97.34, 32.60], [-97.345, 32.555]] },
    { n: 'I-30', w: 2.1, pts: [[-97.55, 32.735], [-97.45, 32.735], [-97.36, 32.745], [-97.28, 32.74], [-97.19, 32.735], [-97.10, 32.735], [-97.02, 32.75], [-96.93, 32.77], [-96.85, 32.785], [-96.80, 32.79], [-96.73, 32.805], [-96.66, 32.83], [-96.60, 32.855], [-96.54, 32.88], [-96.47, 32.90], [-96.40, 32.93], [-96.34, 32.945], [-96.295, 32.96]] },
    { n: 'I-20', w: 2.1, pts: [[-97.55, 32.71], [-97.46, 32.685], [-97.38, 32.665], [-97.30, 32.66], [-97.22, 32.665], [-97.14, 32.665], [-97.06, 32.66], [-96.99, 32.66], [-96.92, 32.665], [-96.85, 32.67], [-96.78, 32.675], [-96.71, 32.70], [-96.64, 32.72], [-96.56, 32.735], [-96.46, 32.735], [-96.36, 32.74], [-96.24, 32.75], [-96.06, 32.765]] },
    { n: 'I-45', w: 2.1, pts: [[-96.80, 32.77], [-96.775, 32.72], [-96.755, 32.665], [-96.73, 32.60], [-96.70, 32.54], [-96.665, 32.48], [-96.63, 32.41], [-96.60, 32.33], [-96.58, 32.26]] },
    { n: 'I-635', w: 1.8, pts: [[-97.038, 32.92], [-96.97, 32.925], [-96.90, 32.93], [-96.83, 32.925], [-96.77, 32.92], [-96.71, 32.905], [-96.66, 32.88], [-96.625, 32.845], [-96.61, 32.80], [-96.625, 32.755], [-96.665, 32.72]] },
    { n: 'I-820', w: 1.8, pts: [[-97.44, 32.68], [-97.475, 32.735], [-97.48, 32.80], [-97.45, 32.85], [-97.39, 32.865], [-97.31, 32.865], [-97.23, 32.86], [-97.19, 32.85]] },
    { n: 'US-287N', w: 1.4, pts: [[-97.345, 32.86], [-97.39, 32.93], [-97.43, 32.99], [-97.472, 33.053], [-97.51, 33.11], [-97.55, 33.17], [-97.586, 33.235], [-97.63, 33.31], [-97.68, 33.40], [-97.70, 33.43]] },
    { n: 'US-287S', w: 1.4, pts: [[-97.44, 32.68], [-97.33, 32.63], [-97.22, 32.60], [-97.10, 32.545], [-96.994, 32.482], [-96.92, 32.435], [-96.87, 32.40], [-96.78, 32.35], [-96.70, 32.31], [-96.60, 32.26]] },
    { n: 'US-75', w: 1.4, pts: [[-96.80, 32.80], [-96.77, 32.86], [-96.75, 32.91], [-96.71, 32.965], [-96.70, 33.02], [-96.68, 33.07], [-96.655, 33.12], [-96.63, 33.165], [-96.615, 33.21], [-96.60, 33.25], [-96.575, 33.30], [-96.55, 33.35], [-96.53, 33.40], [-96.525, 33.43]] },
    { n: 'US-380', w: 1.4, pts: [[-97.85, 33.20], [-97.755, 33.212], [-97.66, 33.228], [-97.586, 33.232], [-97.47, 33.238], [-97.35, 33.235], [-97.24, 33.232], [-97.128, 33.23], [-97.05, 33.228], [-96.985, 33.222], [-96.90, 33.225], [-96.82, 33.228], [-96.72, 33.225], [-96.615, 33.22], [-96.51, 33.205], [-96.42, 33.19], [-96.295, 33.185]] },
    { n: 'US-67', w: 1.4, pts: [[-96.81, 32.76], [-96.89, 32.69], [-96.95, 32.63], [-97.00, 32.555], [-97.02, 32.50], [-97.06, 32.44], [-97.09, 32.41]] },
    { n: 'SH-114', w: 1.3, pts: [[-96.93, 32.85], [-96.99, 32.88], [-97.04, 32.90], [-97.10, 32.935], [-97.16, 32.955], [-97.20, 32.985], [-97.25, 33.01], [-97.35, 33.03], [-97.47, 33.05], [-97.565, 33.079], [-97.67, 33.13], [-97.755, 33.19]] },
    { n: 'SH-183', w: 1.3, pts: [[-97.30, 32.83], [-97.20, 32.835], [-97.08, 32.84], [-96.99, 32.85], [-96.92, 32.84], [-96.87, 32.82]] },
    { n: 'SH-121', w: 1.3, pts: [[-97.28, 32.84], [-97.17, 32.87], [-97.09, 32.905], [-97.045, 32.955]] },
    { n: 'SRT-121', w: 1.3, dash: '5 5', pts: [[-97.045, 32.955], [-96.99, 33.02], [-96.90, 33.06], [-96.82, 33.095], [-96.74, 33.14], [-96.63, 33.19]] },
    { n: 'DNT', w: 1.3, dash: '5 5', pts: [[-96.82, 32.86], [-96.82, 32.95], [-96.825, 33.03], [-96.82, 33.10], [-96.815, 33.18], [-96.80, 33.26], [-96.79, 33.34], [-96.78, 33.43]] },
    { n: 'PGBT', w: 1.3, dash: '5 5', pts: [[-97.045, 32.86], [-97.05, 32.92], [-96.99, 32.985], [-96.90, 33.00], [-96.82, 32.995], [-96.75, 32.99], [-96.68, 32.975], [-96.64, 32.94], [-96.60, 32.90], [-96.56, 32.86]] }
  ];

  var landmarks = [
    { n: 'DFW AIRPORT', ll: [-97.04, 32.899] },
    { n: 'AT&T STADIUM', ll: [-97.095, 32.748], ta: 'a' },
    { n: 'TX MOTOR SPEEDWAY', ll: [-97.283, 33.037] }
  ];

  /* City fields:
     slug, name, county, ll:[lon,lat], anchor: m|s|e (label above / right / left), dx, dy, fs (label size),
     pop, price (median, $), ppsf, dom (days on market), yoy (string),
     tagline, vibe, isd, hoods: [[name, note] x4], schools: [[name, level, grade] x3],
     commute: [DT Dallas, DFW Airport, DT Fort Worth, Legacy West] minutes,
     gallery: [3 photo-slot labels] (optional), featured: 1 (optional) */
  var cities = [
    // ——— DENTON COUNTY ———
    { slug: 'sanger', name: 'Sanger', county: 'denton', ll: [-97.174, 33.363], anchor: 's', dx: 9, dy: 4, fs: 10.5,
      pop: 9900, price: 365000, ppsf: 178, dom: 43, yoy: '+2.1%',
      tagline: 'Gateway to Ray Roberts', isd: 'Sanger ISD',
      vibe: 'Sanger is the last small town before Lake Ray Roberts — a feed-store downtown, FFA barns, and I-35 running you into Denton in fifteen minutes. Lake weekends are the local currency.',
      hoods: [['Downtown Sanger', 'The original grid off Bolivar Street'], ['Sable Creek', 'New-build starter streets'], ['Ray Roberts edge', 'Acreage toward the marina'], ['Indian Springs', 'Established family pocket']],
      schools: [['Sanger High School', 'High', 'B'], ['Sanger Middle School', 'Middle', 'B+'], ['Butterfield Elementary', 'Elementary', 'B+']],
      commute: [55, 45, 62, 35] },
    { slug: 'denton', name: 'Denton', county: 'denton', ll: [-97.133, 33.215], anchor: 'm', dx: 0, dy: -12, fs: 13,
      pop: 158000, price: 385000, ppsf: 196, dom: 33, yoy: '+2.5%',
      tagline: 'College-town soul, courthouse square', isd: 'Denton ISD',
      vibe: 'Denton runs on two universities, a legendary little music scene, and a courthouse square that stays busy after dark. Buyers get historic bungalows, duplex income plays, and new north-side master plans in a single market.',
      hoods: [['Oak-Hickory district', 'Historic bungalows walkable to the square'], ['Southridge', 'Mid-century ranches near the interstate'], ['Robson Ranch', '55+ resort community out west'], ['Rayzor Ranch', 'New mixed-use along University Dr']],
      schools: [['Denton High School', 'High', 'B+'], ['Calhoun Middle School', 'Middle', 'B'], ['Newton Rayzor Elementary', 'Elementary', 'A-']],
      commute: [42, 33, 44, 28], gallery: ['the courthouse square at night', 'Oak Street bungalow row', 'UNT campus green'] },
    { slug: 'aubrey', name: 'Aubrey', county: 'denton', ll: [-96.986, 33.304], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 12800, price: 425000, ppsf: 195, dom: 41, yoy: '+1.8%',
      tagline: 'Horse country, new rooftops', isd: 'Aubrey ISD',
      vibe: 'Aubrey is where the blackland prairie still shows — horse fences and feed stores beside brand-new master plans. You get small-town Friday nights with the Dallas North Tollway extension pulling the metroplex closer every year.',
      hoods: [['Sandbrock Ranch', 'Resort-style master plan on the west side'], ['Silverado', 'Value-minded new builds off the DNT extension'], ['Winn Ridge', 'Starter-friendly streets near 380'], ['Old Town Aubrey', 'Original grid, big trees, small-town bones']],
      schools: [['Aubrey High School', 'High', 'B+'], ['Aubrey Middle School', 'Middle', 'B+'], ['H.L. Brockett Elementary', 'Elementary', 'A-']],
      commute: [48, 38, 58, 27], gallery: ['downtown Aubrey storefronts', 'new-build streetscape', 'horse pasture at golden hour'] },
    { slug: 'little-elm', name: 'Little Elm', county: 'denton', ll: [-96.925, 33.163], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 55400, price: 455000, ppsf: 205, dom: 37, yoy: '+2.1%',
      tagline: 'Frisco\u2019s lakefront neighbor', isd: 'Little Elm ISD',
      vibe: 'Little Elm wraps around Lewisville Lake with an actual beach, a boardwalk, and lakefront patios — rare things in North Texas. Prices run a meaningful step below Frisco next door, which keeps the growth coming.',
      hoods: [['Union Park', 'Amenity-stacked master plan near 380'], ['Paloma Creek', 'Established value play east of the lake'], ['Sunset Pointe', 'Mature streets close to the shoreline'], ['Valencia on the Lake', 'Newer builds with lake access']],
      schools: [['Little Elm High School', 'High', 'B'], ['Walker Middle School', 'Middle', 'B+'], ['Lakeview Elementary', 'Elementary', 'A-']],
      commute: [40, 32, 52, 22], gallery: ['Little Elm Beach boardwalk', 'lakefront patio dining', 'Lewisville Lake at sunset'] },
    { slug: 'the-colony', name: 'The Colony', county: 'denton', ll: [-96.886, 33.089], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 46300, price: 470000, ppsf: 216, dom: 33, yoy: '+2.6%',
      tagline: 'Lake days, Grandscape nights', isd: 'Lewisville ISD',
      vibe: 'The Colony pairs older, affordable lake-adjacent streets with Grandscape — one of the biggest retail-entertainment districts in the country. It\u2019s the rare inner suburb where you can still find a deal walkable to something.',
      hoods: [['The Tribute', 'Links-style golf and lake trails'], ['Austin Ranch', 'Walkable urban village, rental-heavy'], ['Stewart Peninsula', 'Golf-course streets near the shoreline'], ['Legend Crest', 'Established family blocks, LISD schools']],
      schools: [['The Colony High School', 'High', 'B+'], ['Lakeview Middle School', 'Middle', 'B+'], ['Stewart\u2019s Creek Elementary', 'Elementary', 'B+']],
      commute: [33, 26, 46, 14], gallery: ['Grandscape at dusk', 'Tribute golf fairway', 'peninsula shoreline trail'] },
    { slug: 'argyle', name: 'Argyle', county: 'denton', ll: [-97.183, 33.121], anchor: 'e', dx: -9, dy: 4, fs: 12,
      pop: 6400, price: 748000, ppsf: 232, dom: 45, yoy: '+1.2%',
      tagline: 'Acreage living, A-rated schools', isd: 'Argyle ISD',
      vibe: 'Argyle is horse-property Texas with one of the state\u2019s most sought-after small school districts. Custom homes on an acre or more, FFA trailers in the school lot, and Fort Worth or Denton twenty-odd minutes away.',
      hoods: [['Harvest', 'Farm-themed master plan with community garden'], ['5T Ranch', 'Estate lots on the east side'], ['Country Lakes', 'Family-scaled streets off 407'], ['Old Town Argyle', 'Original acreage under mature oaks']],
      schools: [['Argyle High School', 'High', 'A'], ['Argyle Middle School', 'Middle', 'A'], ['Hilltop Elementary', 'Elementary', 'A']],
      commute: [44, 28, 34, 34] },
    { slug: 'northlake', name: 'Northlake', county: 'denton', ll: [-97.262, 33.129], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 12100, price: 585000, ppsf: 210, dom: 42, yoy: '+2.9%',
      tagline: 'Front porches on the 35W corridor', isd: 'Northwest ISD',
      vibe: 'Northlake barely existed a decade ago; now Pecan Square and its neighbors are filling the 35W corridor with front-porch neighborhoods and event lawns. It\u2019s new-build country with Fort Worth commutes.',
      hoods: [['Pecan Square', 'Front-porch master plan, packed events calendar'], ['Harvest', 'Shared with Argyle — farmstand and all'], ['Canyon Falls', 'Trail-laced, spans three towns'], ['FM 407 corridor', 'Acreage and custom builds']],
      schools: [['V.R. Eaton High School', 'High', 'A-'], ['Leo Adams Middle School', 'Middle', 'A-'], ['Lance Thompson Elementary', 'Elementary', 'A']],
      commute: [45, 26, 30, 36] },
    { slug: 'lantana', name: 'Lantana', county: 'denton', ll: [-97.121, 33.092], anchor: 'm', dx: 0, dy: -11, fs: 11,
      pop: 11400, price: 645000, ppsf: 206, dom: 39, yoy: '+1.5%',
      tagline: 'A golf-course village under the oaks', isd: 'Denton ISD',
      vibe: 'Lantana is a single master-planned community that functions like its own town — golf course down the middle, pools and gyms in every village, and a fiercely loyal resident base. HOA-run and proud of it.',
      hoods: [['Bandera', 'Golf-adjacent customs'], ['Reata', 'Family core near the amenity centers'], ['Barrington', 'Larger lots on the south side'], ['Azalea', 'Newer builds near 407']],
      schools: [['Guyer High School', 'High', 'A'], ['Harpool Middle School', 'Middle', 'A'], ['E.P. Rayzor Elementary', 'Elementary', 'A-']],
      commute: [42, 27, 36, 32] },
    { slug: 'highland-village', name: 'Highland Village', county: 'denton', ll: [-97.047, 33.092], anchor: 'e', dx: -9, dy: 13, fs: 10.5,
      pop: 16000, price: 585000, ppsf: 218, dom: 32, yoy: '+2.2%',
      tagline: 'Lakeside cul-de-sacs, LISD schools', isd: 'Lewisville ISD',
      vibe: 'Highland Village is a quiet, nearly built-out town on Lewisville Lake’s south shore — mature trees, top Lewisville ISD campuses, and The Shops giving it a retail heart. Inventory is scarce, and the neighbors prefer it that way.',
      hoods: [['Highland Shores', 'The lakeside master-plan anchor'], ['Castlewood', 'Estate lots under mature oaks'], ['Chapel Hill', 'Gated customs near the bridge'], ['The Shops district', 'Townhomes by retail and trail']],
      schools: [['Marcus High School', 'High', 'A'], ['Briarhill Middle School', 'Middle', 'A-'], ['Highland Village Elementary', 'Elementary', 'A-']],
      commute: [37, 24, 36, 27] },
    { slug: 'trophy-club', name: 'Trophy Club', county: 'denton', ll: [-97.183, 33.005], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 13600, price: 728000, ppsf: 238, dom: 36, yoy: '+2.0%',
      tagline: 'Fairways, Byron Nelson, cul-de-sacs', isd: 'Northwest ISD',
      vibe: 'Built around the only golf course Byron Nelson ever designed, Trophy Club is mature trees, wide cul-de-sacs, and one of the metro\u2019s best-regarded high schools. Fifteen minutes to DFW Airport without the flight path.',
      hoods: [['The Highlands', 'Newer section, amenity pools'], ['Hogan\u2019s Glen', 'Gated, on the Nelson course'], ['Canterbury Hills', 'Original wooded streets'], ['Lakes of Trophy Club', 'Pond-side family blocks']],
      schools: [['Byron Nelson High School', 'High', 'A'], ['Medlin Middle School', 'Middle', 'A'], ['Lakeview Elementary', 'Elementary', 'A']],
      commute: [40, 22, 28, 32] },
    { slug: 'roanoke', name: 'Roanoke', county: 'denton', ll: [-97.226, 33.004], anchor: 'e', dx: -9, dy: 4, fs: 10.5,
      pop: 10200, price: 495000, ppsf: 208, dom: 35, yoy: '+2.6%',
      tagline: 'The Unique Dining Capital of Texas', isd: 'Northwest ISD',
      vibe: 'Roanoke turned its brick Oak Street into a destination restaurant row — the state made the “Unique Dining Capital” title official. Behind the patios: new family streets, Byron Nelson schools, and the 114 corridor’s job engine.',
      hoods: [['Oak Street district', 'Live behind the restaurant row'], ['Fairway Ranch', 'Newer family core off 377'], ['Briarwyck', 'Amenity pocket near Byron Nelson High'], ['The Highlands edge', 'Acreage toward Trophy Club']],
      schools: [['Byron Nelson High School', 'High', 'A'], ['Medlin Middle School', 'Middle', 'A'], ['Roanoke Elementary', 'Elementary', 'A-']],
      commute: [42, 20, 26, 35], gallery: ['Oak Street patios at dusk', 'the downtown water tower', 'Fairway Ranch streetscape'] },
    { slug: 'flower-mound', name: 'Flower Mound', county: 'denton', ll: [-97.097, 33.014], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 81200, price: 668000, ppsf: 228, dom: 31, yoy: '+2.4%',
      tagline: 'Trails, trees, and top schools', isd: 'Lewisville ISD',
      vibe: 'Flower Mound is the polished suburban benchmark of Denton County — 60+ miles of trails, strict development standards, and schools that anchor resale values. The River Walk district added patios and canals to the formula.',
      hoods: [['Bridlewood', 'Golf, equestrian center, mature trees'], ['River Walk', 'Canal-side dining and townhomes'], ['Canyon Falls', 'Newer trail community to the west'], ['Wellington', 'Family staple with pools and ponds']],
      schools: [['Marcus High School', 'High', 'A'], ['Shadow Ridge Middle School', 'Middle', 'A'], ['Bridlewood Elementary', 'Elementary', 'A']],
      commute: [35, 20, 33, 26], gallery: ['River Walk canal patios', 'Bridlewood bridle path', 'Grapevine Lake overlook'] },
    // ——— WISE COUNTY ———
    { slug: 'decatur', name: 'Decatur', county: 'wise', ll: [-97.586, 33.234], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 7600, price: 352000, ppsf: 176, dom: 45, yoy: '+1.6%',
      tagline: 'The pink-courthouse county seat', isd: 'Decatur ISD',
      vibe: 'Decatur is Wise County’s heart — a working courthouse square in pink granite, with coffee, boots, and biscuits where US-287 crosses 380. Acreage buyers get real country with Fort Worth forty minutes down the road.',
      hoods: [['The Square district', 'Victorian blocks around the pink courthouse'], ['Sunset Ridge', 'Newer builds on the west side'], ['Greenwood corridor', 'Acreage north toward the lake'], ['FM 51 south', 'Horse property and long fences']],
      schools: [['Decatur High School', 'High', 'B+'], ['McCarroll Middle School', 'Middle', 'B+'], ['Rann Elementary', 'Elementary', 'A-']],
      commute: [62, 48, 38, 56], gallery: ['the pink granite courthouse', 'square storefronts at dusk', 'FM 51 ranchland'] },
    { slug: 'bridgeport', name: 'Bridgeport', county: 'wise', ll: [-97.755, 33.212], anchor: 'm', dx: 0, dy: -10, fs: 11,
      pop: 6400, price: 312000, ppsf: 164, dom: 48, yoy: '+1.1%',
      tagline: 'Lake country, friendliest prices', isd: 'Bridgeport ISD',
      vibe: 'Bridgeport is the west-side lake town — weekend cabins turned year-round customs on Lake Bridgeport, and a revived brick strip along Halsell Street. Prices here are the county’s most approachable.',
      hoods: [['Lake Bridgeport shores', 'Weekend cabins to year-round customs'], ['Downtown Halsell', 'The revived brick strip'], ['Runaway Bay edge', 'Golf-course lots by the water'], ['East 380 corridor', 'New starter streets']],
      schools: [['Bridgeport High School', 'High', 'B'], ['Bridgeport Middle School', 'Middle', 'B'], ['Bridgeport Elementary', 'Elementary', 'B+']],
      commute: [70, 55, 45, 63], gallery: ['Lake Bridgeport cove', 'Halsell Street brick row', 'sunset over the Wise hills'] },
    { slug: 'rhome', name: 'Rhome', county: 'wise', ll: [-97.472, 33.053], anchor: 's', dx: 9, dy: 4, fs: 10.5,
      pop: 1900, price: 342000, ppsf: 172, dom: 42, yoy: '+2.0%',
      tagline: 'Where 287 meets the metroplex', isd: 'Northwest ISD',
      vibe: 'Rhome sits where 287 meets 114, which makes it Wise County’s fastest on-ramp to the metroplex. Northwest ISD zoning and new-build subdivisions are pulling first-time buyers across the Tarrant line.',
      hoods: [['Shale Creek', 'New-build value in Northwest ISD'], ['Old Rhome', 'The original grid off 287'], ['County-road acreage', 'Room for the horses'], ['114 corridor', 'The growth path toward Boyd']],
      schools: [['Northwest High School', 'High', 'B+'], ['Chisholm Trail Middle School', 'Middle', 'B+'], ['Seven Hills Elementary', 'Elementary', 'B+']],
      commute: [52, 35, 28, 48] },
    { slug: 'boyd', name: 'Boyd', county: 'wise', ll: [-97.565, 33.079], anchor: 'm', dx: 0, dy: -10, fs: 10.5,
      pop: 1500, price: 328000, ppsf: 168, dom: 44, yoy: '+1.7%',
      tagline: 'One stoplight, big skies', isd: 'Boyd ISD',
      vibe: 'Boyd is a one-stoplight town on the Trinity’s west fork where FFA still outranks HOA. Buyers come for the acreage, stay for the quiet, and commute down 114.',
      hoods: [['Downtown Boyd', 'Storefronts along FM 730'], ['Trinity bottoms', 'Acreage toward the west fork'], ['Knob Hill Road', 'Ranchettes north of town'], ['School-side streets', 'Walk to all three campuses']],
      schools: [['Boyd High School', 'High', 'B'], ['Boyd Middle School', 'Middle', 'B'], ['Boyd Elementary', 'Elementary', 'B+']],
      commute: [56, 40, 31, 52] },
    { slug: 'aurora', name: 'Aurora', county: 'wise', ll: [-97.504, 33.058], anchor: 'e', dx: -9, dy: 4, fs: 10.5,
      pop: 1400, price: 425000, ppsf: 186, dom: 46, yoy: '+1.4%',
      tagline: 'Acreage with a UFO legend', isd: 'Northwest ISD',
      vibe: 'Aurora is the hamlet with the 1897 UFO legend and some of the county’s prettiest rolling acreage. No subdivisions to speak of — just long driveways and wide skies, fifteen minutes from Texas Motor Speedway.',
      hoods: [['Old Aurora', 'Near the legend’s cemetery marker'], ['FM 1141 acreage', 'Long driveways, longer sunsets'], ['Pecan Creek lots', 'Wooded homesites'], ['114 frontage', 'Hold-and-wait land plays']],
      schools: [['Northwest High School', 'High', 'B+'], ['Chisholm Trail Middle School', 'Middle', 'B+'], ['Seven Hills Elementary', 'Elementary', 'B+']],
      commute: [51, 34, 29, 47] },
    // ——— COLLIN COUNTY ———
    { slug: 'celina', name: 'Celina', county: 'collin', ll: [-96.784, 33.324], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 34900, price: 638000, ppsf: 224, dom: 44, yoy: '+3.3%',
      tagline: 'The next boomtown north', isd: 'Celina & Prosper ISDs',
      vibe: 'Celina has been America\u2019s fastest-growing city more than once, and the square still does Friday-night markets like the boom never happened. Buy here for the trajectory: the DNT is arriving, and so is everyone else.',
      hoods: [['Light Farms', 'Pools, trails, its own elementary'], ['Mustang Lakes', 'Resort amenities on the east side'], ['Cambridge Crossing', 'Newer phases near Preston Rd'], ['Downtown Celina', 'The square — markets and main-street brick']],
      schools: [['Celina High School', 'High', 'A-'], ['Jerry & Linda Moore Middle School', 'Middle', 'A-'], ['Light Farms Elementary', 'Elementary', 'A']],
      commute: [47, 40, 62, 26], gallery: ['Celina square on market night', 'Light Farms lawn', 'DNT extension northward'] },
    { slug: 'anna', name: 'Anna', county: 'collin', ll: [-96.548, 33.349], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 32200, price: 398000, ppsf: 182, dom: 40, yoy: '+2.2%',
      tagline: 'First-time buyer country', isd: 'Anna ISD',
      vibe: 'Anna is where Collin County still starts under $400K. US-75 runs straight to it, the new-build inventory is deep, and the city is racing to add the retail and parks its rooftops demand.',
      hoods: [['West Crossing', 'Established starter streets'], ['Anacapri', 'Lagoon-anchored newcomer'], ['Sherley Farms', 'New phases near downtown'], ['Villages of Hurricane Creek', 'Larger lots off 455']],
      schools: [['Anna High School', 'High', 'B+'], ['Anna Middle School', 'Middle', 'B+'], ['Joe K. Bryant Elementary', 'Elementary', 'A-']],
      commute: [50, 45, 66, 30] },
    { slug: 'melissa', name: 'Melissa', county: 'collin', ll: [-96.573, 33.286], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 21400, price: 472000, ppsf: 196, dom: 42, yoy: '+2.5%',
      tagline: 'Small-town feel on 75', isd: 'Melissa ISD',
      vibe: 'Melissa keeps a one-district, one-town identity while doubling in size — the cardinal-red water tower says as much. It\u2019s the tidy middle option between McKinney prices and Anna distances.',
      hoods: [['Liberty', 'Amenity-rich family core'], ['North Creek', 'Established east-side streets'], ['Wolf Creek Farms', 'Newer builds with green space'], ['Villages of Melissa', 'Value phases near 121']],
      schools: [['Melissa High School', 'High', 'A-'], ['Melissa Middle School', 'Middle', 'A-'], ['Harry McKillop Elementary', 'Elementary', 'A-']],
      commute: [46, 42, 63, 27] },
    { slug: 'prosper', name: 'Prosper', county: 'collin', ll: [-96.801, 33.236], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 44600, price: 788000, ppsf: 236, dom: 43, yoy: '+1.9%',
      tagline: 'Big lots, bigger master plans', isd: 'Prosper ISD',
      vibe: 'Prosper made its name on quarter-acre-plus lots and a school district families chase across state lines. Windsong Ranch\u2019s crystal lagoon set the amenity arms race; the town still insists on its small-town seal.',
      hoods: [['Windsong Ranch', '2,000 acres and a crystal lagoon'], ['Star Trail', 'Newer luxury phases off the DNT'], ['Whitley Place', 'Creekside lots, stone bridges'], ['Lakes of La Cima', 'Established east-side anchor']],
      schools: [['Prosper High School', 'High', 'A'], ['Walnut Grove High School', 'High', 'A'], ['Reynolds Middle School', 'Middle', 'A']],
      commute: [40, 34, 56, 18], gallery: ['Windsong lagoon', 'Prosper water tower', 'estate-lot streetscape'] },
    { slug: 'mckinney', name: 'McKinney', county: 'collin', ll: [-96.615, 33.198], anchor: 's', dx: 9, dy: 4, fs: 13,
      pop: 224800, price: 535000, ppsf: 214, dom: 35, yoy: '+2.3%', featured: 1,
      tagline: 'Unique by nature — square included', isd: 'McKinney ISD',
      vibe: 'McKinney\u2019s historic square is the best downtown in the northern suburbs — working courthouse, wine bars, and a farmers market with a line. Around it: everything from 1900s bungalows to golf-course master plans.',
      hoods: [['Historic Downtown', 'Square living, festivals, patios'], ['Stonebridge Ranch', '500 acres of lakes and golf'], ['Craig Ranch', 'TPC golf and the corporate corridor'], ['Trinity Falls', 'Newer trail community up 75']],
      schools: [['McKinney Boyd High School', 'High', 'A-'], ['Faubion Middle School', 'Middle', 'B+'], ['Wolford Elementary', 'Elementary', 'A']],
      commute: [37, 33, 55, 16], gallery: ['the McKinney square at night', 'historic-district bungalow', 'Stonebridge Ranch lake'] },
    { slug: 'frisco', name: 'Frisco', county: 'collin', ll: [-96.824, 33.150], anchor: 's', dx: 9, dy: 5, fs: 13,
      pop: 238100, price: 662000, ppsf: 238, dom: 38, yoy: '+2.4%', featured: 1,
      tagline: 'Sports capital of Texas', isd: 'Frisco ISD',
      vibe: 'Frisco built the playbook every suburb now copies: pro sports as city planning. The Star, PGA headquarters, and a school district that opens a new campus most years. Master-planned to the last median — and it works.',
      hoods: [['Fields', 'The new north side, wrapped around PGA HQ'], ['Newman Village', 'Gated, European-inflected customs'], ['Phillips Creek Ranch', 'West-side family favorite'], ['The Rail District', 'Old downtown — breweries and patios']],
      schools: [['Wakeland High School', 'High', 'A'], ['Vandeventer Middle School', 'Middle', 'A'], ['Corbell Elementary', 'Elementary', 'A']],
      commute: [32, 26, 48, 10], gallery: ['The Star district', 'Rail District patios', 'PGA Frisco fairways'] },
    { slug: 'fairview', name: 'Fairview', county: 'collin', ll: [-96.616, 33.145], anchor: 's', dx: 9, dy: 4, fs: 11,
      pop: 11300, price: 715000, ppsf: 226, dom: 47, yoy: '+1.4%',
      tagline: 'Country quiet between two booms', isd: 'Lovejoy & McKinney ISDs',
      vibe: 'Fairview holds the line at half-acre lots and dark-sky ordinances while Allen and McKinney boom on either side. The Lovejoy ISD half of town is one of the metro\u2019s quietest luxury markets.',
      hoods: [['Heritage Ranch', '55+ golf and guard gate'], ['Sloan Creek', 'Lovejoy-zoned customs'], ['Ascot Heath', 'Estate lots under oaks'], ['Fairview Meadows', 'East-side acreage']],
      schools: [['Lovejoy High School', 'High', 'A'], ['Willow Springs Middle School', 'Middle', 'A'], ['Puster Elementary', 'Elementary', 'A']],
      commute: [36, 34, 54, 15] },
    { slug: 'allen', name: 'Allen', county: 'collin', ll: [-96.671, 33.103], anchor: 'e', dx: -9, dy: 4, fs: 13,
      pop: 111600, price: 548000, ppsf: 212, dom: 32, yoy: '+2.2%',
      tagline: 'One town, one team', isd: 'Allen ISD',
      vibe: 'Allen runs one giant high school on purpose — the $60M stadium tells you how that\u2019s going. Underneath the football is a genuinely complete suburb: watters Creek shopping, mature neighborhoods, easy 75 access.',
      hoods: [['Twin Creeks', 'Golf-course spine of west Allen'], ['StarCreek', 'Newer luxury near 121'], ['Watters Crossing', 'Walkable to Watters Creek shops'], ['Montgomery Farm', 'Eco-minded, creekside']],
      schools: [['Allen High School', 'High', 'A'], ['Ereckson Middle School', 'Middle', 'A'], ['Bolin Elementary', 'Elementary', 'A']],
      commute: [31, 30, 50, 12] },
    { slug: 'lucas', name: 'Lucas', county: 'collin', ll: [-96.577, 33.084], anchor: 's', dx: 9, dy: 4, fs: 11,
      pop: 9100, price: 948000, ppsf: 258, dom: 52, yoy: '+1.6%',
      tagline: 'Acreage estates, Lovejoy schools', isd: 'Lovejoy ISD',
      vibe: 'Lucas is one-acre-minimum country inside the Collin County boom — barns, pools, and long driveways, fifteen minutes from Allen\u2019s big-box everything. Lovejoy ISD keeps demand permanently ahead of supply.',
      hoods: [['Forest Grove', 'Wooded acreage estates'], ['Brockdale Estates', 'Near the Lavon shoreline'], ['Stinson Highlands', 'Custom builds on the ridge'], ['Lovejoy corridor', 'Acreage along Estates Pkwy']],
      schools: [['Lovejoy High School', 'High', 'A'], ['Sloan Creek Intermediate', 'Intermediate', 'A'], ['Hart Elementary', 'Elementary', 'A']],
      commute: [35, 34, 54, 17] },
    { slug: 'parker', name: 'Parker', county: 'collin', ll: [-96.625, 33.055], anchor: 'e', dx: -9, dy: 4, fs: 11,
      pop: 5800, price: 1050000, ppsf: 262, dom: 58, yoy: '+1.1%',
      tagline: 'Ranchette living beside Southfork', isd: 'Plano & Allen ISDs',
      vibe: 'Parker is the town where Southfork Ranch sits — which tells you the look: white fences, long horizons, million-dollar ranchettes minutes from Plano. No commercial strip, and residents like it that way.',
      hoods: [['Kings Crossing', 'Gated estate lots'], ['Southfork corridor', 'Ranchettes along FM 2514'], ['Rolling Meadows Estates', 'Acre-plus customs'], ['Hidden Creek', 'Wooded cul-de-sacs']],
      schools: [['Plano East Senior High', 'High', 'A-'], ['Murphy Middle School', 'Middle', 'A-'], ['Boggess Elementary', 'Elementary', 'A']],
      commute: [33, 32, 52, 15] },
    { slug: 'st-paul', name: 'St. Paul', county: 'collin', ll: [-96.551, 33.041], anchor: 'e', dx: -9, dy: 4, fs: 10.5,
      pop: 1150, price: 618000, ppsf: 222, dom: 49, yoy: '+1.3%',
      tagline: 'A one-square-mile secret', isd: 'Wylie ISD',
      vibe: 'St. Paul is barely a square mile of quiet streets tucked between Wylie and Lucas — one of Collin County\u2019s smallest towns and determined to stay that way. Large lots, low turnover, zero retail.',
      hoods: [['St. Paul Estates', 'The town core'], ['Founders Grove', 'Half-acre originals'], ['FM 982 corridor', 'Acreage edges'], ['Lakeview lanes', 'East toward Lavon']],
      schools: [['Wylie High School', 'High', 'A-'], ['McMillan Junior High', 'Middle', 'B+'], ['Akin Elementary', 'Elementary', 'A-']],
      commute: [36, 35, 55, 18] },
    { slug: 'plano', name: 'Plano', county: 'collin', ll: [-96.699, 33.020], anchor: 'e', dx: -9, dy: 5, fs: 13,
      pop: 293200, price: 562000, ppsf: 218, dom: 30, yoy: '+2.8%',
      tagline: 'The proven blue-chip suburb', isd: 'Plano ISD',
      vibe: 'Plano is the suburb that already made it: Fortune 500 headquarters, the Legacy West district, and forty years of neighborhoods that hold value like index funds. Mature trees, remodeled ranches, and everything within 15 minutes.',
      hoods: [['Legacy West', 'High-rise living over shops and HQs'], ['Willow Bend', 'Estate blocks near the mall\u2019s rebirth'], ['Deerfield', 'Iconic holiday-lights streets'], ['Lakeside on Preston', 'Ponds and mature customs']],
      schools: [['Plano West Senior High', 'High', 'A'], ['Rice Middle School', 'Middle', 'A'], ['Huffman Elementary', 'Elementary', 'A']],
      commute: [26, 24, 44, 6], gallery: ['Legacy West at dusk', 'Deerfield in December', 'Arbor Hills trailhead'] },
    { slug: 'murphy', name: 'Murphy', county: 'collin', ll: [-96.613, 33.015], anchor: 'e', dx: -9, dy: 4, fs: 11,
      pop: 20800, price: 588000, ppsf: 206, dom: 33, yoy: '+1.9%',
      tagline: 'Quiet streets between 75 and 78', isd: 'Plano & Wylie ISDs',
      vibe: 'Murphy is a bedroom community in the truest sense — big brick homes on 8,000-plus-foot lots, Plano ISD zoning on the west side, and almost nothing to do after 9pm. That\u2019s the pitch, and it lands.',
      hoods: [['Maxwell Creek', 'Trail-laced with a big amenity center'], ['Rolling Ridge', 'Established oversized lots'], ['North Hill', 'Newer builds near FM 544'], ['Glen Ridge Estates', 'Quiet cul-de-sac pocket']],
      schools: [['McMillen High School', 'High', 'A-'], ['Murphy Middle School', 'Middle', 'A-'], ['Hunt Elementary', 'Elementary', 'A-']],
      commute: [30, 30, 49, 13] },
    { slug: 'wylie', name: 'Wylie', county: 'collin', ll: [-96.539, 33.015], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 63500, price: 468000, ppsf: 198, dom: 34, yoy: '+2.7%',
      tagline: 'Wide awake on Lavon\u2019s shore', isd: 'Wylie ISD',
      vibe: '\u201CWide Awake Wylie\u201D kept its brick downtown on Ballard Avenue and grew a real city around it. Two lakes on either side, a hometown school district, and prices that undercut the DNT corridor by $150K.',
      hoods: [['Inspiration', 'Hilltop pools overlooking Lavon'], ['Woodbridge', '36-hole golf spanning the creek'], ['Dominion of Pleasant Valley', 'Newer south-side phases'], ['Downtown Ballard', 'Brick storefronts, Olde City Park']],
      schools: [['Wylie East High School', 'High', 'B+'], ['Cooper Junior High', 'Middle', 'B+'], ['Birmingham Elementary', 'Elementary', 'A-']],
      commute: [33, 33, 52, 17], gallery: ['Ballard Avenue brick row', 'Lavon Lake marina', 'Olde City Park pavilion'] },
    // ——— TARRANT COUNTY ———
    { slug: 'fort-worth', name: 'Fort Worth', county: 'tarrant', ll: [-97.331, 32.755], anchor: 'm', dx: 0, dy: -12, fs: 16,
      pop: 1013000, price: 368000, ppsf: 188, dom: 38, yoy: '+1.7%', featured: 1,
      tagline: 'Cowtown cool, big-city value', isd: 'Fort Worth ISD',
      vibe: 'Fort Worth is the last big American city that still feels like itself — stockyards and honky-tonks, a world-class museum district, and neighborhoods from craftsman Fairmount to ranch-house Tanglewood at half of Dallas prices.',
      hoods: [['Fairmount', 'Craftsman bungalows, Magnolia Ave nightlife'], ['Arlington Heights', 'Classic streets near the museums'], ['Tanglewood', 'Legacy ranches under live oaks'], ['Walsh', 'Fiber-first master plan out west']],
      schools: [['Paschal High School', 'High', 'B+'], ['McLean Middle School', 'Middle', 'B+'], ['Tanglewood Elementary', 'Elementary', 'A']],
      commute: [34, 26, 6, 49], gallery: ['the Stockyards herd drive', 'Magnolia Avenue patios', 'Kimbell Art Museum lawn'] },
    { slug: 'arlington', name: 'Arlington', county: 'tarrant', ll: [-97.108, 32.735], anchor: 'm', dx: 0, dy: 18, fs: 13,
      pop: 398000, price: 345000, ppsf: 182, dom: 32, yoy: '+2.1%',
      tagline: 'Big-league city between the downtowns', isd: 'Arlington ISD',
      vibe: 'Arlington stacks AT&T Stadium, Globe Life Field, and Six Flags into one entertainment district, with a huge spread of honestly-priced neighborhoods around it. UTA keeps the middle of the city young; Viridian is rewriting the north side.',
      hoods: [['Viridian', 'Lakes, a sailing center, master-plan north'], ['Interlochen', 'Canal streets, legendary holiday lights'], ['Entertainment District', 'Walk to the ballparks'], ['Southwest Arlington', 'Martin-zoned family blocks']],
      schools: [['Martin High School', 'High', 'A-'], ['Young Junior High', 'Middle', 'B+'], ['Butler Elementary', 'Elementary', 'A-']],
      commute: [22, 17, 15, 42], gallery: ['AT&T Stadium plaza', 'Globe Life Field gates', 'River Legacy trails'] },
    { slug: 'north-richland-hills', name: 'North Richland Hills', county: 'tarrant', ll: [-97.229, 32.834], anchor: 'e', dx: -12, dy: 5, fs: 10,
      pop: 71000, price: 415000, ppsf: 196, dom: 29, yoy: '+2.4%',
      tagline: 'Northeast Tarrant’s steady hub', isd: 'Birdville ISD',
      vibe: 'North Richland Hills is the mid-cities workhorse — NRH2O summers, TEXRail straight into DFW Airport, and block after block of solid brick inventory. Hometown’s canal-side cottages give it a new-urbanist heart.',
      hoods: [['Hometown', 'Canal-side cottages and lawns'], ['Iron Horse', 'Golf-course redevelopment corridor'], ['Smithfield', 'Old-town grid at the TEXRail stop'], ['Forest Glenn', 'Established north-side family blocks']],
      schools: [['Richland High School', 'High', 'B+'], ['Smithfield Middle School', 'Middle', 'B+'], ['Green Valley Elementary', 'Elementary', 'A-']],
      commute: [31, 15, 14, 38] },
    { slug: 'lake-worth', name: 'Lake Worth', county: 'tarrant', ll: [-97.445, 32.805], anchor: 's', dx: 9, dy: 4, fs: 10.5,
      pop: 4900, price: 315000, ppsf: 172, dom: 35, yoy: '+1.2%',
      tagline: 'Small city on the water', isd: 'Lake Worth ISD',
      vibe: 'Lake Worth is a pocket-sized city on its namesake lake, minutes from the Naval Air Station and downtown Fort Worth. Modest ranch homes, boat slips, and some of Tarrant County\u2019s most approachable prices.',
      hoods: [['The Shores', 'Closest streets to the water'], ['Indian Oaks', 'Established mid-century blocks'], ['Marina district', 'Slips and weekend traffic'], ['Boat Club corridor', 'Northward toward Eagle Mountain']],
      schools: [['Lake Worth High School', 'High', 'B'], ['Lucyle Collins Middle School', 'Middle', 'B'], ['Effie Morris Elementary', 'Elementary', 'B+']],
      commute: [42, 32, 14, 56] },
    { slug: 'azle', name: 'Azle', county: 'tarrant', ll: [-97.545, 32.895], anchor: 'm', dx: 0, dy: -10, fs: 10.5,
      pop: 14000, price: 335000, ppsf: 174, dom: 40, yoy: '+1.5%',
      tagline: 'Eagle Mountain’s hometown shore', isd: 'Azle ISD',
      vibe: 'Azle is the little lake city on Eagle Mountain’s west shore — boat dealers on Main Street, Cross Timbers acreage out the back door, and downtown Fort Worth twenty-odd minutes down 199.',
      hoods: [['Lakeside coves', 'Boat docks off Boat Club Road'], ['Downtown Main Street', 'The original strip on 199'], ['Cross Timbers acreage', 'Horse property to the northwest'], ['Ash Creek', 'Established family streets']],
      schools: [['Azle High School', 'High', 'B'], ['Azle Junior High', 'Middle', 'B'], ['Walnut Creek Elementary', 'Elementary', 'B+']],
      commute: [48, 38, 24, 60] },
    { slug: 'keller', name: 'Keller', county: 'tarrant', ll: [-97.252, 32.935], anchor: 'e', dx: -9, dy: 4, fs: 12,
      pop: 46600, price: 622000, ppsf: 216, dom: 34, yoy: '+2.1%',
      tagline: 'Old town heart, big backyard', isd: 'Keller ISD',
      vibe: 'Keller balances a walkable Old Town strip with half-acre neighborhoods that still feel semi-rural. Keller ISD\u2019s reputation and quick 114 access to the airport keep it on nearly every northeast-Tarrant shortlist.',
      hoods: [['Hidden Lakes', 'Golf-adjacent family core'], ['Marshall Ridge', 'Newer trail-side phases'], ['Old Town Keller', 'Walk to the town center strip'], ['Bear Creek Estates', 'Wooded oversized lots']],
      schools: [['Keller High School', 'High', 'A'], ['Keller Middle School', 'Middle', 'A-'], ['Ridgeview Elementary', 'Elementary', 'A-']],
      commute: [37, 20, 22, 38] },
    { slug: 'southlake', name: 'Southlake', county: 'tarrant', ll: [-97.134, 32.941], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 31800, price: 1350000, ppsf: 312, dom: 49, yoy: '+2.9%',
      tagline: 'Dragon country, Town Square living', isd: 'Carroll ISD',
      vibe: 'Southlake is the metroplex\u2019s benchmark luxury suburb: Carroll ISD\u2019s Dragons, Town Square\u2019s open-air brick blocks, and estate neighborhoods where teardowns start at seven figures. Five minutes to DFW\u2019s north entrance.',
      hoods: [['Timarron', 'Golf and pools, walkable to schools'], ['Carillon', 'Brownstones and new customs'], ['Shady Oaks', 'Estate lots under the canopy'], ['Town Square district', 'Live over the shops']],
      schools: [['Carroll Senior High School', 'High', 'A+'], ['Dawson Middle School', 'Middle', 'A'], ['Rockenbaugh Elementary', 'Elementary', 'A']],
      commute: [32, 12, 24, 32], gallery: ['Town Square fountain', 'Timarron fairway homes', 'Dragon Stadium on Friday'] },
    { slug: 'grapevine', name: 'Grapevine', county: 'tarrant', ll: [-97.078, 32.934], anchor: 's', dx: 9, dy: 4, fs: 12,
      pop: 51000, price: 548000, ppsf: 242, dom: 29, yoy: '+3.1%',
      tagline: 'Main Street between two runways', isd: 'Grapevine-Colleyville ISD',
      vibe: 'Grapevine\u2019s historic Main Street — wine rooms, the vintage railroad, a real ice cream parlor — sits ten minutes from every gate at DFW. Lakefront trails on one side, Christmas-capital energy all December.',
      hoods: [['Historic Township', 'Main Street porches and tasting rooms'], ['Silver Lake', 'Near the lake and the resorts'], ['Glade Crossing', 'Established GCISD family blocks'], ['Lakeshore', 'Grapevine Lake weekends']],
      schools: [['Grapevine High School', 'High', 'A-'], ['Grapevine Middle School', 'Middle', 'A-'], ['Dove Elementary', 'Elementary', 'A-']],
      commute: [28, 8, 26, 28], gallery: ['Main Street at Christmas', 'Grapevine Vintage Railroad', 'lakeside cypress trail'] },
    { slug: 'colleyville', name: 'Colleyville', county: 'tarrant', ll: [-97.148, 32.881], anchor: 'e', dx: -9, dy: 4, fs: 12,
      pop: 27000, price: 952000, ppsf: 262, dom: 44, yoy: '+2.2%',
      tagline: 'Estate lots under the canopy', isd: 'Grapevine-Colleyville ISD',
      vibe: 'Colleyville is what quiet money buys in northeast Tarrant: gated courts, acre lots under mature oaks, and no through-traffic to speak of. The restaurant row along Colleyville Boulevard keeps it from being sleepy.',
      hoods: [['Montclair Parc', 'Gated estates off Hall-Johnson'], ['Clairemont', 'Manicured custom courts'], ['Caldwell\u2019s Creek', 'Creekside family classic'], ['Whittier Heights', 'Newer luxury pocket']],
      schools: [['Colleyville Heritage High School', 'High', 'A'], ['Colleyville Middle School', 'Middle', 'A'], ['Bransford Elementary', 'Elementary', 'A']],
      commute: [30, 12, 22, 32] },
    { slug: 'bedford', name: 'Bedford', county: 'tarrant', ll: [-97.143, 32.844], anchor: 'e', dx: -9, dy: 4, fs: 11,
      pop: 49900, price: 386000, ppsf: 198, dom: 28, yoy: '+2.6%',
      tagline: 'Mid-cities sweet spot', isd: 'Hurst-Euless-Bedford ISD',
      vibe: 'Bedford is the mid-cities value thesis: 1980s brick homes with real trees, equidistant to both downtowns, and a 10-minute run to DFW Airport. Remodel inventory does brisk business here.',
      hoods: [['Bedford Heights', 'Central, tree-lined originals'], ['Stonegate Colony', 'Updated 80s classics'], ['Meadow Creek', 'Near parks and the library'], ['Central Drive corridor', 'Convenience-first blocks']],
      schools: [['L.D. Bell High School', 'High', 'B+'], ['Bedford Junior High', 'Middle', 'B+'], ['Meadow Creek Elementary', 'Elementary', 'A-']],
      commute: [27, 12, 17, 34] },
    { slug: 'euless', name: 'Euless', county: 'tarrant', ll: [-97.082, 32.837], anchor: 's', dx: 9, dy: 4, fs: 11,
      pop: 61500, price: 374000, ppsf: 202, dom: 27, yoy: '+2.3%',
      tagline: 'The metroplex\u2019s true middle', isd: 'Hurst-Euless-Bedford ISD',
      vibe: 'Euless sits at the geographic center of the metroplex, and the market knows it — starter homes and townhomes move in under a month. Trinity High\u2019s legendary Polynesian football pipeline is a genuine point of pride.',
      hoods: [['Parks at Texas Star', 'Wrapping the golf complex'], ['Bear Creek', 'Trail-connected family streets'], ['Glade Parks', 'New townhomes by the shops'], ['Midway Park', 'Affordable originals']],
      schools: [['Trinity High School', 'High', 'B+'], ['Euless Junior High', 'Middle', 'B'], ['Oakwood Terrace Elementary', 'Elementary', 'B+']],
      commute: [24, 9, 19, 32] },
    { slug: 'hurst', name: 'Hurst', county: 'tarrant', ll: [-97.170, 32.824], anchor: 'm', dx: 0, dy: 15, fs: 11,
      pop: 40400, price: 356000, ppsf: 192, dom: 29, yoy: '+1.9%',
      tagline: 'First-ring value in Mid-Cities', isd: 'Hurst-Euless-Bedford ISD',
      vibe: 'Hurst is the oldest of the HEB trio and prices like it — solid mid-century ranches, mature pecans, and the NE Mall retail engine. A remodeler\u2019s market fifteen minutes from either downtown\u2019s paycheck.',
      hoods: [['Bellaire Park', 'Mid-century core near schools'], ['Redbud Hills', 'Rolling originals north of 183'], ['Mayfair', 'Updated ranch blocks'], ['Precinct Line corridor', 'Retail-adjacent convenience']],
      schools: [['L.D. Bell High School', 'High', 'B+'], ['Hurst Junior High', 'Middle', 'B'], ['Bellaire Elementary', 'Elementary', 'B+']],
      commute: [26, 13, 15, 36] },
    { slug: 'westlake', name: 'Westlake', county: 'tarrant', ll: [-97.195, 32.985], anchor: 'e', dx: -9, dy: 4, fs: 11,
      pop: 1780, price: 2950000, ppsf: 512, dom: 88, yoy: '+4.1%',
      tagline: 'Texas\u2019s most exclusive zip code', isd: 'Westlake Academy & Carroll ISD',
      vibe: 'Westlake routinely posts the highest median home price in Texas — Vaquero\u2019s guard-gated Fazio golf estates set the tone, and the town-run Westlake Academy is a free IB school with a waitlist to match.',
      hoods: [['Vaquero', 'Guard-gated Fazio golf estates'], ['Glenwyck Farms', 'Acre-plus customs'], ['Entrada', 'Spanish-village mixed use'], ['Quail Hollow', 'New estate enclave']],
      schools: [['Westlake Academy (IB)', 'K-12', 'A+'], ['Carroll Senior High School', 'High', 'A+'], ['Walnut Grove Elementary', 'Elementary', 'A']],
      commute: [38, 18, 26, 31] },
    // ——— DALLAS COUNTY ———
    { slug: 'coppell', name: 'Coppell', county: 'dallas', ll: [-97.015, 32.955], anchor: 's', dx: 9, dy: 4, fs: 11,
      pop: 42600, price: 642000, ppsf: 232, dom: 28, yoy: '+2.5%',
      tagline: 'Small-town polish by the airport', isd: 'Coppell ISD',
      vibe: 'Coppell is a school-district town with a farmers-market heart, boxed in by the airport and three highways — which is exactly why inventory stays scarce. Old Town\u2019s cottages and porches carry the brand.',
      hoods: [['Old Town Coppell', 'Farmers market and cottage streets'], ['Cypress Waters', 'Lakeside offices, lofts, patios'], ['Riverchase', 'Golf-loop classic'], ['Lakes of Coppell', 'Pond-laced family core']],
      schools: [['Coppell High School', 'High', 'A'], ['Coppell Middle East', 'Middle', 'A'], ['Austin Elementary', 'Elementary', 'A']],
      commute: [22, 9, 29, 20] },
    { slug: 'irving', name: 'Irving', county: 'dallas', ll: [-96.970, 32.856], anchor: 'm', dx: 0, dy: -10, fs: 13,
      pop: 258100, price: 418000, ppsf: 214, dom: 31, yoy: '+2.8%',
      tagline: 'Canals, towers, crossroads', isd: 'Irving ISD',
      vibe: 'Irving is two cities: Las Colinas\u2019 canals, corporate towers, and the Toyota Music Factory on one side; original 1950s neighborhoods reinventing themselves on the other. Nowhere in DFW is better connected.',
      hoods: [['Las Colinas', 'Canals, towers, Music Factory'], ['Valley Ranch', 'Canal-path family staple'], ['Heritage District', 'Original downtown, rail stop'], ['University Hills', 'Rolling streets near UD']],
      schools: [['MacArthur High School', 'High', 'B'], ['Travis Middle School', 'Middle', 'B+'], ['Las Colinas Elementary', 'Elementary', 'A-']],
      commute: [14, 10, 25, 24], gallery: ['Las Colinas canal gondola', 'Music Factory marquee night', 'Mandalay Canal arches'] },
    { slug: 'dallas', name: 'Dallas', county: 'dallas', ll: [-96.797, 32.777], anchor: 's', dx: 10, dy: 5, fs: 16,
      pop: 1312000, price: 438000, ppsf: 226, dom: 36, yoy: '+2.0%',
      tagline: 'The Big D itself', isd: 'Dallas ISD',
      vibe: 'Dallas contains fifty markets in one: Lakewood Tudors, Bishop Arts bungalows, Uptown high-rises, Preston Hollow estates. If you want walkability, architecture, or a skyline view, this is where the metroplex keeps it.',
      hoods: [['Lakewood', '1930s Tudors near White Rock Lake'], ['Bishop Arts', 'Indie storefronts, Oak Cliff bungalows'], ['M Streets', 'Gabled charmers off Greenville Ave'], ['Preston Hollow', 'Estate lots inside the loop']],
      schools: [['Woodrow Wilson High School', 'High', 'B+'], ['J.L. Long Middle School', 'Middle', 'B+'], ['Lakewood Elementary', 'Elementary', 'A']],
      commute: [8, 20, 33, 25], gallery: ['skyline from the Trinity', 'Bishop Arts mural block', 'White Rock Lake spillway'] },
    { slug: 'sachse', name: 'Sachse', county: 'dallas', ll: [-96.595, 32.978], anchor: 'm', dx: 0, dy: 15, fs: 11,
      pop: 29900, price: 498000, ppsf: 202, dom: 33, yoy: '+2.4%',
      tagline: 'The in-between town growing up', isd: 'Garland & Wylie ISDs',
      vibe: 'Sachse straddles the Dallas\u2013Collin county line and quietly delivers what its flashier neighbors charge more for: newer brick homes, the PGBT a minute away, and The Station district finally giving it a downtown.',
      hoods: [['Woodbridge', 'Golf community spilling in from Wylie'], ['The Station', 'New town-center district'], ['Jackson Meadows', 'Newer family phases'], ['Heritage Park', 'Established core blocks']],
      schools: [['Sachse High School', 'High', 'B+'], ['Hudson Middle School', 'Middle', 'B+'], ['Sewell Elementary', 'Elementary', 'A-']],
      commute: [29, 30, 48, 15] },
    { slug: 'rowlett', name: 'Rowlett', county: 'dallas', ll: [-96.564, 32.903], anchor: 'e', dx: -9, dy: 4, fs: 12,
      pop: 67900, price: 428000, ppsf: 196, dom: 32, yoy: '+2.4%',
      tagline: 'Peninsula city on Ray Hubbard', isd: 'Garland ISD',
      vibe: 'Rowlett owns more Lake Ray Hubbard shoreline than anyone, and the Bayside peninsula is slowly becoming the waterfront district it was always supposed to be. DART rail downtown is the quiet superpower.',
      hoods: [['Bayside', 'Peninsula parks on the lake'], ['Waterview', 'Golf and amenity village'], ['Harmony Hill', 'New builds near the PGBT'], ['Lake Country Estates', 'Shoreline originals']],
      schools: [['Rowlett High School', 'High', 'B+'], ['Coyle Middle School', 'Middle', 'B'], ['Herfurth Elementary', 'Elementary', 'B+']],
      commute: [24, 32, 44, 22] },
    // ——— ROCKWALL COUNTY ———
    { slug: 'rockwall', name: 'Rockwall', county: 'rockwall', ll: [-96.460, 32.931], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 53100, price: 522000, ppsf: 208, dom: 37, yoy: '+2.6%', featured: 1,
      tagline: 'Harbor lights east of the lake', isd: 'Rockwall ISD',
      vibe: 'Rockwall\u2019s Harbor district — lighthouse, boardwalk, restaurants on the water — gives the east side of the lake a downtown to be proud of. Add a courthouse square and top-third schools, and it sells itself.',
      hoods: [['The Harbor district', 'Waterfront dining and the boardwalk'], ['Chandlers Landing', 'Sail-club gated originals'], ['Breezy Hill', 'Newer estate-feel phases'], ['Stone Creek', 'Family core off 205']],
      schools: [['Rockwall High School', 'High', 'A-'], ['Cain Middle School', 'Middle', 'A-'], ['Dorothy Smith Pullen Elementary', 'Elementary', 'A']],
      commute: [28, 37, 49, 28], gallery: ['the Harbor lighthouse', 'courthouse square evening', 'Ray Hubbard sail race'] },
    { slug: 'heath', name: 'Heath', county: 'rockwall', ll: [-96.475, 32.837], anchor: 's', dx: 9, dy: 4, fs: 11,
      pop: 11500, price: 782000, ppsf: 234, dom: 48, yoy: '+1.8%',
      tagline: 'Yacht-club quiet, Rockwall schools', isd: 'Rockwall ISD',
      vibe: 'Heath is Rockwall County\u2019s estate tier: golf-and-yacht-club living, acre lots rolling down to the water, and a strict no-hurry attitude toward development. The lagoon community brought the first real new-build wave.',
      hoods: [['Buffalo Creek', 'Fairway customs'], ['Heath Golf & Yacht Club', 'Lagoon-side new builds'], ['Willowcreek Estates', 'Acreage toward the shore'], ['Terry Lane corridor', 'Quiet custom pockets']],
      schools: [['Rockwall-Heath High School', 'High', 'A-'], ['Cain Middle School', 'Middle', 'A-'], ['Amy Parks-Heath Elementary', 'Elementary', 'A']],
      commute: [30, 39, 51, 31] },
    // ——— KAUFMAN COUNTY ———
    { slug: 'forney', name: 'Forney', county: 'kaufman', ll: [-96.472, 32.748], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 42400, price: 386000, ppsf: 172, dom: 39, yoy: '+2.9%',
      tagline: 'Antique capital, new roofs', isd: 'Forney ISD',
      vibe: 'Forney — the official Antique Capital of Texas — is now one of the metro\u2019s fastest-growing value markets. Master plans line US-80, and buyers get 2,500 square feet for what a starter costs inside the loop.',
      hoods: [['Gateway Parks', 'Amenity-forward new phase'], ['Devonshire', 'Stacked amenities, mature now'], ['Windmill Farms', 'Deep value inventory'], ['Travis Ranch', 'Lakeside-of-Hubbard value play']],
      schools: [['North Forney High School', 'High', 'B+'], ['Brown Middle School', 'Middle', 'B+'], ['Claybon Elementary', 'Elementary', 'A-']],
      commute: [24, 34, 46, 31] },
    // ——— ELLIS COUNTY ———
    { slug: 'midlothian', name: 'Midlothian', county: 'ellis', ll: [-96.994, 32.482], anchor: 'm', dx: 0, dy: -10, fs: 12,
      pop: 43100, price: 462000, ppsf: 188, dom: 41, yoy: '+2.3%',
      tagline: 'Cement city turned family favorite', isd: 'Midlothian ISD',
      vibe: 'Midlothian built the concrete that built the metroplex; now it\u2019s building neighborhoods — acre lots and new master plans on the rolling southwest edge, with both downtowns a straight 35-minute shot away.',
      hoods: [['MidTowne', 'New-urbanist streets near Heritage High'], ['Lawson Farms', 'Established family value'], ['Valley Ridge', 'Newer phases with hill views'], ['Old Town Midlothian', 'Original grid near 8th Street']],
      schools: [['Midlothian Heritage High School', 'High', 'A'], ['Walnut Grove Middle School', 'Middle', 'A-'], ['LaRue Miller Elementary', 'Elementary', 'A-']],
      commute: [31, 40, 32, 48] }
  ];

  /* Actively-selling master-planned communities — prices & builder counts are PLACEHOLDERS */
  var newBuilds = [
    { name: 'Pecan Square', city: 'northlake', from: '$480s', builders: 9, status: 'NOW SELLING', note: 'Front-porch streets, a coworking barn, and a packed events lawn.' },
    { name: 'Sandbrock Ranch', city: 'aubrey', from: '$400s', builders: 7, status: 'NOW SELLING', note: 'Resort pool, fishing lakes, and an on-site elementary.' },
    { name: 'Union Park', city: 'little-elm', from: '$420s', builders: 6, status: 'MODELS OPEN', note: 'Hilltop amenity village with a 35-acre central park off 380.' },
    { name: 'Harvest', city: 'argyle', from: '$450s', builders: 8, status: 'FINAL PHASE', note: 'The farm-themed plan — community garden, farmstand, and all.' },
    { name: 'Walsh', city: 'fort-worth', from: '$500s', builders: 10, status: 'NOW SELLING', note: 'Fiber-first master plan on 7,200 west-side acres.' },
    { name: 'Viridian', city: 'arlington', from: '$420s', builders: 8, status: 'NOW SELLING', note: 'Lakes, a sailing center, and River Legacy trail links.' },
    { name: 'Ventana', city: 'fort-worth', from: '$390s', builders: 5, status: 'MODELS OPEN', note: 'Rolling-hill value southwest of the 820 loop.' },
    { name: 'Shale Creek', city: 'rhome', from: '$330s', builders: 4, status: 'NOW SELLING', note: 'Northwest ISD value at the 287/114 junction.' },
    { name: 'Sunset Ridge', city: 'decatur', from: '$340s', builders: 3, status: 'MODELS OPEN', note: 'New rooftops a mile from the pink courthouse.' },
    { name: 'Fields', city: 'frisco', from: '$700s', builders: 12, status: 'NOW SELLING', note: 'Wrapped around the new PGA of America headquarters.' },
    { name: 'Light Farms', city: 'celina', from: '$500s', builders: 8, status: 'FINAL PHASE', note: 'Trail-laced plan with its own on-site elementary.' },
    { name: 'Windsong Ranch', city: 'prosper', from: '$600s', builders: 9, status: 'NOW SELLING', note: 'The crystal lagoon that started the amenity arms race.' },
    { name: 'Trinity Falls', city: 'mckinney', from: '$450s', builders: 8, status: 'NOW SELLING', note: 'Riverside trails and pocket parks up US-75.' },
    { name: 'Anacapri', city: 'anna', from: '$360s', builders: 5, status: 'NOW SELLING', note: 'Lagoon living at Collin County’s entry price.' },
    { name: 'Harmony Hill', city: 'rowlett', from: '$430s', builders: 4, status: 'NOW SELLING', note: 'New streets a minute off the PGBT.' },
    { name: 'The Station', city: 'sachse', from: '$400s', builders: 3, status: 'MODELS OPEN', note: 'Townhomes in the new town-center district.' },
    { name: 'Gateway Parks', city: 'forney', from: '$330s', builders: 6, status: 'NOW SELLING', note: 'Deep value and stacked amenities east on US-80.' },
    { name: 'Heath Golf & Yacht Club', city: 'heath', from: '$600s', builders: 4, status: 'NOW SELLING', note: 'Fairways and a lagoon above Ray Hubbard.' },
    { name: 'MidTowne', city: 'midlothian', from: '$400s', builders: 5, status: 'MODELS OPEN', note: 'New-urbanist blocks near Heritage High.' }
  ];

  var bySlug = {};
  for (var i = 0; i < cities.length; i++) bySlug[cities[i].slug] = cities[i];

  return {
    bounds: { lonMin: -98.00, lonMax: -96.01, latMax: 33.47, latMin: 32.13 },
    counties: counties, lakes: lakes, roads: roads, landmarks: landmarks,
    cities: cities, bySlug: bySlug, newBuilds: newBuilds,
    hubs: ['Downtown Dallas', 'DFW Airport', 'Downtown Fort Worth', 'Legacy West \u00B7 Plano']
  };
})();